extends:
  - airbnb-base
env:
  browser: true
  es2021: true
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-restricted-syntax:
    - "error"
    - "ForInStatement"
    - "LabeledStatement"
    - "WithStatement"
settings:
  react:
    version: "detect"
